create table account (initial_balance numeric(38,2), status boolean, client_id bigint, id bigint generated by default as identity, number varchar(255) unique, type varchar(255) check (type in ('SAVINGS','CURRENT')), primary key (id));
create table transaction (amount numeric(38,2), balance numeric(38,2), performed_at date, status boolean, account_id bigint, id bigint generated by default as identity, type varchar(255) check (type in ('DEPOSIT','WITHDRAW')), primary key (id));
create index idx_account_number on account (number);
create index idx_account_client_id on account (client_id);
alter table if exists transaction add constraint FK6g20fcr3bhr6bihgy24rq1r1b foreign key (account_id) references account;
